openapi:
  version: 3.0.0
info:
  title: RENEGADA PRATICA 07
  description: Uma API REST desenvolvida para aula
  version: 0.1.0
servers:
  - url: http://localhost:3000
    description: Ambiente de desenvolvimento
tags:
  name: produtos
paths:
  /produtos:
    get:
      tags:
        - produtos
      requestBody:
      responses: 
        200:
          description: "Uma lista de produtos"
          content: 
            application/json:
              schemas:
                $ref: '#/components/schemas/ArrayOfProdutos'
    post:
      tags:
        - produtos
      requestBody:
        description: "Um JSON com dados do novo produto"
        required: true
        content:
          application/json:
            schemas:
              $ref: '#/components/schemas/Produto'
      responses:
        201:
          description: "Produto criado com sucesso"
          content:
            application/json:
              schemas:
                $ref: '#/components/schemas/Produto'
        422:
          description: "Nome e preço são obrigatórios"
  /produtos/{produtoId}:
    get:
      tags:
        - produtos
      parameters:
        in: path
        name: produtoId
        schemas: integer
        required: true
        description: "Id do produto a ser buscado"
      requestBody:
      responses:
        200:
          description: "Um JSON com os dados do produto encontrado"
          content:
            application/json:
              schemas:
                $ref: '#/components/Produto'
        404:
          description:
          content:
    put:
    delete: 
components: